### ISSUE TITLE
neetoEditor revamp

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#1100]
This issue aims to revamp neetoEditor to solve all the UI, UX, and performance challenges and make it on par with the competitors.

Video explanation: https://abhay-ashokan.neetorecord.com/watch/dd81c94a-72e9-4e99-a0d5-74806a92d676

- [x] https://github.com/bigbinary/neeto-editor/issues/1163
  - One of the main difficulties of using neetoEditor is that it can be only used as an uncontrolled component. This has a negative developer experience and needs the developers to directly use the editor API to mutate the content.
  - The controlled version of neetoEditor should not impact the performance.
- [x] https://github.com/bigbinary/neeto-editor/issues/1134
- [x] https://github.com/bigbinary/neeto-editor/issues/1135
- [x] UI Improvement
  - [x] https://github.com/bigbinary/neeto-editor/issues/1105
  - [x] https://github.com/bigbinary/neeto-editor/issues/1106
  - [x] https://github.com/bigbinary/neeto-editor/issues/1112
  - [x] https://github.com/bigbinary/neeto-editor/issues/1122
  - [x] https://github.com/bigbinary/neeto-editor/issues/1121
  - Audit individual editor elements and improve the writing experience.
  - [x] https://github.com/bigbinary/neeto-editor/issues/1108
  - [x] https://github.com/bigbinary/neeto-editor/issues/1115
  - [x] https://github.com/bigbinary/neeto-editor/issues/1156
  - [x] https://github.com/bigbinary/neeto-editor/issues/1157
- [x] https://github.com/bigbinary/neeto-editor/issues/1158
- Improving the writing experience:
  - [x] https://github.com/bigbinary/neeto-molecules/issues/1347

---

1. Why do people prefer other editors over neetoEditor?

---

- [x] UI Improvements round 2
  - [x] https://github.com/bigbinary/neeto-editor/issues/1159
  - [x] https://github.com/bigbinary/neeto-editor/issues/1160
  - [x] https://github.com/bigbinary/neeto-editor/issues/1161
  - [x] https://github.com/bigbinary/neeto-editor/issues/1162

---

- We can release the new changes in a beta branch and directly use it in neetoChangelog. This would iteratively improve the editor experience before finally releasing it to production.

**References**

1. https://templates.tiptap.dev/
3. Notion

@neerajsingh0101 LMK your thoughts.

enhancement _t

cc: @sumanranjanpanda, @sandip-mane, @Aditya-Bakshi5, @deepakjosp

**Comment by neerajsingh0101** [comment]
@AbhayVAshokan https://neerajsingh0101.neetorecord.com/watch/e3883d0a-4452-4c43-b891-a18d716d97e0

**Comment by AbhayVAshokan** [comment]
@neerajsingh0101 

Understood. The idea of this issue is to make sure that we have a good experience while using neetoEditor and not push newer features.

1. **Temporarily disable slash commands**: As you mentioned, slash commands are less likely to be used by users who are writing blogs. Let's temporarily disable the slash commands and push more on using the menu. If it looks good to everyone, we shall permanently remove it.
2. **Improving the contrast**: The menu can be much better. Increase the contrast of buttons, and increase the size of buttons. Audit every element rendered inside neetoEditor and make sure it stands out.
3. **Audit all editor options**: Audit individual options (Table, mentions, emoji, etc) and make sure that they have a usable UI and good accessibility (arrow keys and tabs).
4. **Misc**: Improve the writing experience. Write help documents in neetoKB and figure out the common issues while writing the document and improve it.

cc: @deepakjosp, @sumanranjanpanda

**Comment by neerajsingh0101** [comment]
@AbhayVAshokan sounds good.

**Comment by praveen-murali-ind** [comment]
@neerajsingh0101 @AbhayVAshokan Please check let me know your thoughts. 

https://praveen-murali.neetorecord.com/watch/5bc8c4d3-9edc-4fdd-bd9a-947092ddeaa3

Before and after - [Figma](https://www.figma.com/design/datgPdCE0B1IEmeWW9ELS8/Editor?node-id=0-1&t=QiW3exW0Zpoa1tT1-1)

**Comment by neerajsingh0101** [comment]
@praveen-murali-ind All the points you mentioned are valid. All the suggestions look solid. Let's roll with it.

**Comment by praveen-murali-ind** [comment]
@AbhayVAshokan @deepakjosp Please add the following issues to the Neeto Editor project board or to Abhay's board.

https://github.com/bigbinary/neeto-editor/issues/1122
https://github.com/bigbinary/neeto-editor/issues/1131
https://github.com/bigbinary/neeto-editor/issues/1126
https://github.com/bigbinary/neeto-editor/issues/1130
https://github.com/bigbinary/neeto-editor/issues/1132
https://github.com/bigbinary/neeto-editor/issues/1123
https://github.com/bigbinary/neeto-editor/issues/1133
https://github.com/bigbinary/neeto-editor/issues/1134
https://github.com/bigbinary/neeto-editor/issues/1135

**Comment by deepakjosp** [comment]
@AbhayVAshokan I've merged the feature branch to the main branch. For the rest of the sub issues let's create PR to the main branch.

**Comment by deepakjosp** [comment]
@AbhayVAshokan closing the epic since we completed all the sub issues.
