### ISSUE TITLE
Reducing the bundle size

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#1123]
<img width="1552" alt="image" src="https://github.com/bigbinary/neeto-editor/assets/35297280/40a2377b-d02e-4fd5-8658-20c7dd47a157">

- [x] https://github.com/bigbinary/neeto-editor/issues/1124
- [ ] ~https://github.com/bigbinary/neeto-editor/issues/1130~
- [x] https://github.com/bigbinary/neeto-editor/issues/1126
- [x] https://github.com/bigbinary/neeto-editor/issues/1131
- [x] https://github.com/bigbinary/neeto-editor/issues/1127
- [ ] ~https://github.com/bigbinary/neeto-editor/issues/1132~
- [x] https://github.com/bigbinary/neeto-editor/issues/1133

priority _t epic _t

@deepakjosp, @josephmathew900 please LMK if you have any other pointers.
cc: @neerajsingh0101, @sumanranjanpanda

**Comment by deepakjosp** [comment]
@AbhayVAshokan, closing the epic since all the child issues are done.
