### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#405]
Design: https://www.figma.com/file/Ebh2R78Ia9FEVpC4tw6d3N/03-Layouts?node-id=1114%3A2422

- [x] #406
- [x] #407
- [x] #408
  - Enhance the experience of editing captions (similar to BaseCamp).
  - Move image menu options to a three-dot menu on the top right corner of the image.
  - Image alignment: Instead of `float`ing the image to the sides, `align` it to the sides.
  - Uploaded images must be aligned to left by default.
  - Upload modal: Rename `Proceed` to `Done` and align the options to the left.
- [x] #420
  - Remove the `defaults` prop.
  - Add a `config` prop which can override the config of any of the default extensions.
- [x] https://github.com/bigbinary/neeto-editor/issues/455
  - Feature: attach files. The files would be inserted to the bottom of the editor.
  - Drag and drop files into the editor.
  - Option to clear all attachments.

**Post Release**
- [x] Update package verifier in neetoCommons.
- [x] Update the editor UI in neetoKB.

References:
1. https://github.com/bigbinary/neeto-editor/issues/394
2. https://github.com/bigbinary/neeto-kb-web/issues/2472
3. https://github.com/bigbinary/neeto-engineering-ui-ux/issues/18
