### ISSUE TITLE
Keyboard shortcuts and tooltip customisation for Menu component items.

### ISSUE THREAD

**Issue by mohitharshan123** [neetozone/neeto-editor#531]
Ref :https://www.loom.com/share/b54f8ba37f1f40918fc0ef68c3d7a0c9

**Action Items**
- [x] #553 
- [x] #555 
- [x] https://github.com/bigbinary/neeto-editor/issues/566

**Comment by AbhayVAshokan** [comment]
@mohitharshan123 please explain more.

**Comment by mohitharshan123** [comment]
> @mohitharshan123 please explain more.

@AbhayVAshokan Added a loom video in description.

**Comment by AbhayVAshokan** [comment]
@mohitharshan123 all the requirements are satisfied and the same will be released in the compliance today's compliance PR (25 Jan).

Documentation
Tooltip: https://neeto-editor.vercel.app/?path=/docs/walkthroughs-menu--menu
Keyboard shortcuts: https://neeto-editor.vercel.app/?path=/docs/accessibility-keyboard-shortcuts--keyboard-shortcuts

**Comment by mohitharshan123** [comment]
> @mohitharshan123 all the requirements are satisfied and the same will be released in the compliance today's compliance PR (25 Jan).
> 
> Documentation Tooltip: https://neeto-editor.vercel.app/?path=/docs/walkthroughs-menu--menu Keyboard shortcuts: https://neeto-editor.vercel.app/?path=/docs/accessibility-keyboard-shortcuts--keyboard-shortcuts

@AbhayVAshokan Can you please check this: https://neeto-editor.onrender.com/?path=/story/walkthroughs-menutypes-headless-menu--headless-menu

- [ ] After opening the emoji picker, it is not getting closed.
- [ ] Emoji picker tooltip is not updating after passing tooltips prop.
- [ ] In macOs shortcuts are not Cmd+Shift , but Cmd+Option. Is the documentation updated for this?
- [ ] Emoji picker is not opening with Cmd+Shift+E in macOs.

**Comment by AbhayVAshokan** [comment]
@gaagul we need to take up these issues with priority. Please create an issue with a checklist referring to the above comment. Let's get this fixed and released with priority.

1. It is specific to the headless menu type. It's working fine in the fixed menu.
2. The documentation is outdated and needs to be updated.
3. It is specific to the headless menu type. It needs to be fixed. The shortcut is Cmd+Option+E.
4. Needs to be fixed in neetoEditor.

Before raising the PR please verify that every keyboard shortcut is mapped properly to each menu type.

**Comment by gaagul** [comment]
@mohitharshan123 This  [PR](https://github.com/bigbinary/neeto-editor/pull/581) fixes all the above mentioned issues.
