### ISSUE TITLE
File Attachments - UI Audit

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#545]
@goutham-subramanyam _a can you please perform a UI audit for the `Attachments` component and add your suggestions to the below action items:

Please have a look at this video for context: https://vimeo.com/789557479/82bb3d97a3

Figma: https://www.figma.com/file/Mfgurc6h4V776Rl3iKzcbP/neeto-Attachments?node-id=41%3A769
Discussion: https://github.com/bigbinary/neeto-engineering-ui-ux/issues/18

---

**Action Items**
- [x] #548
  - Use: https://github.com/corygibbons/react-file-icon
  - Ref: 
![image](https://user-images.githubusercontent.com/35297280/212104558-f2570124-b9fe-4567-a356-4fc82586d54b.png)

- [x] Add white background color to Attachment and AttachmentProgress
 
<img width="937" alt="Screenshot 2023-01-17 at 4 39 25 PM" src="https://user-images.githubusercontent.com/70290286/212884260-610b8dc4-5cd3-4448-a986-a5a200e1ce65.png">

- [x] Changes to attachment icons
  - Add color `#4558f9` to all the icons. This is the neetoUI primary color 500.
  - Add an icon for `AttachmentProgress` component. The `type` can be `document` since it is generic.

- [x] Storybook changes
  - Add a margin bottom for "With Custom Upload Button".
  - The dropzone bottom is overflowing in the "With custom drop zone" story.

- [x] Drag and drop changes
  - Update the border width to 3px.
  - Update the background color to `rgb(var(--neeto-ui-primary-100))`.

- [x] Editor changes
  - Update the Attachment icon in Menubar to the clip icon in the Figma design. You can directly export the component from Figma and add it to `lib/icons` folder. We shall add it to neetoIcons once this is finalized.

**Comment by goutham-subramanyam** [comment]
@AbhayVAshokan _a Please watch the [loom video](https://www.loom.com/share/6be66744364447b8925bc6717e77e82b) and update the action items as you see fit.

**Comment by AbhayVAshokan** [comment]
@goutham-subramanyam nice video. A small doubt though: https://vimeo.com/790032824/b0662ec7e7

**Comment by AbhayVAshokan** [comment]
@gaagul _a we need to fix the issues of audit. The rest of the issues can be taken up together.
@goutham-subramanyam please check the previous comment.

**Comment by goutham-subramanyam** [comment]
> @goutham-subramanyam nice video. A small doubt though: https://vimeo.com/790032824/b0662ec7e7

@AbhayVAshokan Makes sense. We can remove the smaller dropzone.

**Comment by gaagul** [comment]
@AbhayVAshokan @goutham-subramanyam 
<img width="562" alt="Screenshot 2023-01-20 at 10 03 38 AM" src="https://user-images.githubusercontent.com/70290286/213617979-7123ff2a-ff3a-4507-bb17-5b7e868be943.png">
This is the neetoUI primary color 500 given to the icons, I don't think this looks as intended, I feel like we will have to define custom styles for different file extensions.

**Comment by AbhayVAshokan** [comment]
@gaagul while preparing the action items, I added the neetoUI primary color checklist. What I meant was to make it look like the last item in this screenshot. Check all the different available customizations. The problem with the default behavior is that certain icons are gray and the rest are colored. We need to bring a consistency.
<img width="983" alt="image" src="https://user-images.githubusercontent.com/35297280/213620769-ded8ffc7-bbe4-40e2-88f9-f6c26891856f.png">

Ref: https://react-file-icon.netlify.app/

**Comment by gaagul** [comment]
Closed with #564
