### ISSUE TITLE
Frontend packages standardization

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#602]
Frontend packages standardization

### Code quality
- [x] #622
- [x] Use zustand for state management. Remove the use of contexts.

### Dead code removal
- [x] #603
- [x] #604
- [x] #605

### Dependency management
- [x] Move dependencies to `devDependencies` this will speed up package installation time. We don't need dependencies as we are serving bundles. Try to move packages to peerDependencies if the package exists on host project too. Refer: [neetoui](https://github.com/bigbinary/neeto-ui/blob/main/package.json), [neeto-commons-frontend](https://github.com/bigbinary/neeto-commons-frontend/blob/main/package.json)
- [x] #606

### General enhancements
- [x] Clean up documentation & include exported functions, development & release instructions.
- [x] #607
- [x] Have a mechanism to test changes without depending on a host project and yalc: example: [neeto-team-members-frontend](https://github.com/bigbinary/neeto-team-members-frontend/tree/main/example)
- [x] Have type declaration for all exports: example: [neetoui](https://github.com/bigbinary/neeto-ui/blob/main/index.d.ts)

### Building & releasing
- [x] Standardize release process: release on merge. Example: [neetoui](https://github.com/bigbinary/neeto-ui/blob/main/.github/workflows/publish.yml)
- [x] Use rollup for bundling
- [x] Export ESM bundles

_Originally posted by @Amaljith-K in https://github.com/bigbinary/neeto-engineering-web/issues/282#issuecomment-1415911052_

**Comment by AbhayVAshokan** [comment]
@gaagul _a please go through the checklist and mark the ones that are already complete. Please raise issues to track the remaining work.

epic _t

**Comment by gaagul** [comment]
@AbhayVAshokan _a Are we using eslint and prettier config from wheel? 
I have created issues for rest of the remaining work in the checklist.
Should I add nv2 tags to the created issues?

**Comment by AbhayVAshokan** [comment]
1. Please refer to the `eslint` folder and `prettierrc` file https://github.com/bigbinary/neeto-commons-frontend/tree/main/configs. The configs are now served from neeto-commons-frontend. The changes in the `eslint/helpers.js` file needs to stay as it is due to the difference in folder structure between a neeto product and a nano.
2. Yes please add `nv2` tags to the created issues.

@gaagul _a

**Comment by Amaljith-K** [comment]
@gaagul could you please tell me when this will be finished?

**Comment by gaagul** [comment]
> @gaagul could you please tell me when this will be finished?

I will finish it by today itself. 
I am verifying the eslint and prettier configuration right now, once it is done the epic issue can be closed.

**Comment by gaagul** [comment]
@AbhayVAshokan All the checklists have been completed, Can we close this issue now?

**Comment by AbhayVAshokan** [comment]
Great. Closing as completed.
