### ISSUE TITLE
Release new changes

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#814]
Take up this change once Neenu has completing rolling out neeto-editor-engine in all the neeto products.

- [x] Merge `784-update-direct-uploads-endpoint` branch to `main`: @AbhayVAshokan.
- [x] Add neetoEditor back to compliance.
- [x] #819
- [x] Roll out the `isMenuCollapsible` prop to all the neeto products (wherever necessary).

@gaagul _a

**Comment by AbhayVAshokan** [comment]
@gaagul let's take up this issue this week. For the forth point, got through all the implementations of neetoEditor and decide where to make the necessary change.
